In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv('breast_cancer_data.csv')
print(data.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

In [3]:
print(data.shape)
data.drop("id",axis=1,inplace=True)
print(data.shape)

(569, 33)
(569, 32)


TypeError: data type not understood

In [5]:
data.drop(columns=data.columns[-1], axis=1, inplace=True)
data.describe()

radius_mean  texture_mean  perimeter_mean    area_mean  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  fractal_dimension_mean  ...  radius_worst  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       texture_worst  perimeter_worst   area_worst  smoothness_worst  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       compactness_worst  concavity_worst  concave points_worst  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       symmetry_worst  fractal_dimension_worst  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [31]:
data.describe(include=all)

TypeError: data type not understood

In [6]:
X=data.iloc[:,1:]
y=data["diagnosis"]
print(X.shape)
print(y.shape)
print(y)

(569, 30)
(569,)
0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object


In [7]:
y[y=="M"]=1
y[y=="B"]=0
print(y)
y= y.astype("category")

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: object


C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [8]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size = 0.15,random_state=42)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters = {'penalty': ['l1','l2'],"fit_intercept":[True,False],"C" :np.logspace(-4,4,16),'solver' : ['liblinear'],
              'max_iter' : [500,1000]
             }
logreg_clf = GridSearchCV(LogisticRegression(),parameters, scoring="f1",n_jobs=-1,cv=5)
logreg_clf.fit(X_train,Y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': array([1.00000000e-04, 3.414...
       1.35935639e-02, 4.64158883e-02, 1.58489319e-01, 5.41169527e-01,
       1.84784980e+00, 6.30957344e+00, 2.15443469e+01, 7.35642254e+01,
       2.51188643e+02, 8.57695899e+02, 2.92864456e+03, 1.00000000e+04]),
                         'fit_intercept': [True, False],
                    

In [10]:
from sklearn.model_selection import cross_val_score
score  = cross_val_score(logreg_clf, X_train, Y_train,scoring='accuracy',n_jobs=-1)

In [11]:
print(f'The mean Cross-Valiation Score is {score.mean()}')
print(f'The Training Score is {logreg_clf.score(X_train, Y_train)}')

The mean Cross-Valiation Score is 0.9606743986254296
The Training Score is 0.9611111111111111


In [12]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
test_pred = logreg_clf.predict(X_test)
auc = roc_auc_score(Y_test, test_pred)
print(f"The score on the Test-dataset is {logreg_clf.score(X_test, Y_test)}")
print(f"The ROC_AUC score on the Test-dataset is {auc}")
print(confusion_matrix(Y_test,test_pred))

The score on the Test-dataset is 0.9333333333333333
The ROC_AUC score on the Test-dataset is 0.9375
[[54  0]
 [ 4 28]]


In [17]:
from sklearn.svm import SVC
clf = SVC()
grid = {'C' : [1e2, 1e3, 5e3, 1e4, 5e4, 1e5],
       'gamma' : [1e-3, 5e-4, 1e-4, 5e-3]}
SVC_clf = GridSearchCV(clf, grid,n_jobs=-1)
SVC_clf.fit(X_train, Y_train)


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [100.0, 1000.0, 5000.0, 10000.0, 50000.0,
                               100000.0],
                         'gamma': [0.001, 0.0005, 0.0001, 0.005]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [21]:
score  = cross_val_score(SVC_clf, X_train, Y_train,scoring='accuracy',n_jobs=-1)
print(f'The mean Cross-Valiation Score is {score.mean()}')
print(f'The Training Score is {SVC_clf.score(X_train, Y_train)}')

The mean Cross-Valiation Score is 0.9419243986254295
The Training Score is 0.9937888198757764


In [19]:
test_pred = SVC_clf.predict(X_test)
auc = roc_auc_score(Y_test, test_pred)
print(f"The score on the Test-dataset is {SVC_clf.score(X_test, Y_test)}")
print(f"The ROC_AUC score on the Test-dataset is {auc}")
print(confusion_matrix(Y_test,test_pred))

The score on the Test-dataset is 0.9534883720930233
The ROC_AUC score on the Test-dataset is 0.9375
[[54  0]
 [ 4 28]]


In [22]:
from sklearn.ensemble import RandomForestClassifier
params={'bootstrap': [True, False],'max_depth': [10, 20, 30, None],'max_features': ['auto', 'sqrt'],'min_samples_leaf': [1, 2, 4],'min_samples_split': [2, 5, 10],'n_estimators': [200, 400, 600]}
rand_clf = GridSearchCV(RandomForestClassifier(), params,n_jobs=-1)
rand_clf.fit(X_train,Y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              ra

In [23]:
test_pred = rand_clf.predict(X_test)
auc = roc_auc_score(Y_test, test_pred)
print(f"The score on the Test-dataset is {rand_clf.score(X_test, Y_test)}")
print(f"The ROC_AUC score on the Test-dataset is {auc}")
print(confusion_matrix(Y_test,test_pred))

The score on the Test-dataset is 0.9534883720930233
The ROC_AUC score on the Test-dataset is 0.9438657407407408
[[53  1]
 [ 3 29]]


In [25]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(
estimators=[('lr', logreg_clf), ('rf', rand_clf), ('svc', SVC_clf)],voting='hard',n_jobs=-1)
voting_clf.fit(X_train, Y_train)

VotingClassifier(estimators=[('lr',
                              GridSearchCV(cv=5, error_score=nan,
                                           estimator=LogisticRegression(C=1.0,
                                                                        class_weight=None,
                                                                        dual=False,
                                                                        fit_intercept=True,
                                                                        intercept_scaling=1,
                                                                        l1_ratio=None,
                                                                        max_iter=100,
                                                                        multi_class='auto',
                                                                        n_jobs=None,
                                                                        penalty='l2',
                       

In [27]:
test_pred = voting_clf.predict(X_test)
auc = roc_auc_score(Y_test, test_pred)
print(f"The score on the Test-dataset is {voting_clf.score(X_test, Y_test)}")
print(f"The ROC_AUC score on the Test-dataset is {auc}")
print(confusion_matrix(Y_test,test_pred))

The score on the Test-dataset is 0.9534883720930233
The ROC_AUC score on the Test-dataset is 0.9375
[[54  0]
 [ 4 28]]


In [28]:
import pickle
pickle.dump(voting_clf,open('cancer_voting_clf.pkl','wb'))